#!/bin/bash

# Copyright (C) 2018-2019  yaofei zheng
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

create_time="$(stat -c %y "$1")"
tidy --char-encoding utf8 --indent auto --indent-spaces 4 --quiet yes --tidy-mark false -asxml "$1" > "$1.xhtml5temp"
mv "$1.xhtml5temp" "$1"
touch -d "$create_time" "$1"
