#!/bin/bash
create_time="$(stat -c %y "$1")"
tidy --char-encoding utf-8 --indent auto --indent-spaces 4 --quiet yes --tidy-mark false -asxml "$1" > "$1.xhtml5temp"
mv "$1.xhtml5temp" "$1"
touch -d "$create_time" "$1"
